FROM node:22-alpine AS build
WORKDIR /web
COPY apps/web/package.json apps/web/package-lock.json ./
RUN npm ci
COPY apps/web ./
RUN npm run build

FROM node:22-alpine
WORKDIR /web
COPY --from=build /web ./
EXPOSE 3000
CMD ["npm", "run", "start"]
